# Generated by Django 5.2.6 on 2026-02-26 15:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai", "AI"),
                            ("ml", "Machine Learning"),
                            ("ds", "Data Science"),
                            ("nlp", "Natural Language Processing"),
                            ("cv", "Computer Vision"),
                            ("rl", "Reinforcement Learning"),
                            ("education", "교육"),
                            ("career", "경력"),
                            ("project", "프로젝트"),
                            ("other", "기타"),
                        ],
                        max_length=50,
                        verbose_name="카테고리",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now, verbose_name="작성일")),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="이미지 URL",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="관련 링크",
                    ),
                ),
                ("is_published", models.BooleanField(default=True, verbose_name="공개 여부")),
                ("is_featured", models.BooleanField(default=False, verbose_name="추천 글")),
                ("view_count", models.PositiveIntegerField(default=0, verbose_name="조회수")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "verbose_name": "블로그 포스트",
                "verbose_name_plural": "블로그 포스트",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="이메일")),
                ("name", models.CharField(blank=True, max_length=100, verbose_name="이름")),
                ("is_active", models.BooleanField(default=True, verbose_name="구독 활성화")),
                ("subscribed_at", models.DateTimeField(auto_now_add=True, verbose_name="구독일")),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True, verbose_name="구독 해지일")),
                ("unsubscribe_token", models.UUIDField(default=uuid.uuid4, verbose_name="구독 해지 토큰")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP 주소")),
            ],
            options={
                "verbose_name": "뉴스레터 구독",
                "verbose_name_plural": "뉴스레터 구독",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                ("company", models.CharField(blank=True, max_length=100, verbose_name="회사명")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="연락처")),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("lecture", "강의 문의"),
                            ("consulting", "컨설팅 문의"),
                            ("collaboration", "협업 제안"),
                            ("media", "미디어/인터뷰 문의"),
                            ("general", "일반 문의"),
                            ("other", "기타"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="문의 유형",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="제목")),
                ("message", models.TextField(verbose_name="내용")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP 주소")),
                ("user_agent", models.TextField(blank=True, verbose_name="사용자 에이전트")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="문의일")),
                ("is_processed", models.BooleanField(default=False, verbose_name="처리 여부")),
                ("processed_at", models.DateTimeField(blank=True, null=True, verbose_name="처리일")),
                ("notes", models.TextField(blank=True, verbose_name="관리자 메모")),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="처리자",
                    ),
                ),
            ],
            options={
                "verbose_name": "문의",
                "verbose_name_plural": "문의",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP 주소")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="이메일")),
                ("attempt_count", models.PositiveIntegerField(default=1, verbose_name="시도 횟수")),
                ("last_attempt", models.DateTimeField(auto_now=True, verbose_name="마지막 시도")),
                ("is_blocked", models.BooleanField(default=False, verbose_name="차단 여부")),
                ("block_reason", models.CharField(blank=True, max_length=200, verbose_name="차단 사유")),
            ],
            options={
                "verbose_name": "문의 시도 로그",
                "verbose_name_plural": "문의 시도 로그",
                "unique_together": {("ip_address", "email")},
            },
        ),
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP 주소")),
                ("user_agent", models.TextField(verbose_name="사용자 에이전트")),
                ("referer", models.URLField(blank=True, verbose_name="참조 URL")),
                ("page_path", models.CharField(max_length=500, verbose_name="페이지 경로")),
                ("visit_time", models.DateTimeField(auto_now_add=True, verbose_name="방문 시간")),
                ("session_id", models.CharField(blank=True, max_length=100, verbose_name="세션 ID")),
            ],
            options={
                "verbose_name": "사이트 방문",
                "verbose_name_plural": "사이트 방문",
                "indexes": [
                    models.Index(fields=["ip_address", "visit_time"], name="api_sitevis_ip_addr_49cb96_idx"),
                    models.Index(fields=["page_path", "visit_time"], name="api_sitevis_page_pa_7bfb6a_idx"),
                ],
            },
        ),
    ]
