# Generated by Django 5.2.6 on 2026-02-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="author",
            field=models.CharField(default="이호진", max_length=100, verbose_name="작성자"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="likes",
            field=models.PositiveIntegerField(default=0, verbose_name="좋아요"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name="슬러그"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="태그"),
        ),
    ]
