# Generated by Django 5.2.11 on 2026-03-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_blogpost_author_blogpost_likes_blogpost_slug_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(fields=["is_published", "-date"], name="api_blogpos_is_publ_f2d92d_idx"),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(fields=["category"], name="api_blogpos_categor_83b24e_idx"),
        ),
    ]
