# Generated by Django 5.2.11 on 2026-03-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_blogpost_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="user_agent",
            field=models.CharField(blank=True, max_length=500, verbose_name="사용자 에이전트"),
        ),
    ]
