# Generated by Django 5.2.12 on 2026-03-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_contact_user_agent_max_length_and_slug_retry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="link",
        ),
    ]
