# Generated by Django 5.2.12 on 2026-03-17 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_blogpost_link_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("message", models.TextField(verbose_name="내용")),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "Info"), ("success", "Success"), ("warning", "Warning"), ("error", "Error")],
                        default="info",
                        max_length=10,
                        verbose_name="레벨",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[("system", "시스템"), ("blog", "블로그"), ("contact", "문의"), ("admin", "관리자")],
                        default="system",
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="링크")),
                ("is_read", models.BooleanField(default=False, verbose_name="읽음 여부")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="읽은 시간")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_read", "-created_at"], name="api_notific_user_id_4b7939_idx")
                ],
            },
        ),
    ]
