# Generated by Django 5.2.12 on 2026-03-18 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_add_notification_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("system_enabled", models.BooleanField(default=True, verbose_name="시스템 알림")),
                ("blog_enabled", models.BooleanField(default=True, verbose_name="블로그 알림")),
                ("contact_enabled", models.BooleanField(default=True, verbose_name="문의 알림")),
                ("admin_enabled", models.BooleanField(default=True, verbose_name="관리자 알림")),
                ("email_enabled", models.BooleanField(default=False, verbose_name="이메일 알림")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "알림 설정",
                "verbose_name_plural": "알림 설정",
            },
        ),
    ]
