# Generated by Django 5.2.12 on 2026-03-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_notificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="content_html",
            field=models.TextField(blank=True, default="", verbose_name="HTML 내용"),
        ),
    ]
