# Generated by Django 5.2.12 on 2026-03-19 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_add_content_html_to_blogpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author_name", models.CharField(max_length=100, verbose_name="작성자")),
                ("content", models.TextField(verbose_name="내용")),
                ("likes", models.PositiveIntegerField(default=0, verbose_name="좋아요")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="api.blogcomment",
                        verbose_name="상위 댓글",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_comments",
                        to="api.blogpost",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "블로그 댓글",
                "verbose_name_plural": "블로그 댓글",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP 주소")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_likes",
                        to="api.blogpost",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "블로그 좋아요",
                "verbose_name_plural": "블로그 좋아요",
            },
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP 주소")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to="api.blogcomment",
                        verbose_name="댓글",
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글 좋아요",
                "verbose_name_plural": "댓글 좋아요",
            },
        ),
        migrations.AddIndex(
            model_name="blogcomment",
            index=models.Index(fields=["post", "-created_at"], name="api_blogcom_post_id_020100_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="bloglike",
            unique_together={("post", "ip_address")},
        ),
        migrations.AlterUniqueTogether(
            name="commentlike",
            unique_together={("comment", "ip_address")},
        ),
    ]
