# Generated by Django 6.0.3 on 2026-03-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_add_blog_like_comment_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcomment",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name="IP 주소"),
        ),
    ]
