# Generated by Django 6.0.3 on 2026-03-25 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_add_ip_address_to_blogcomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bloglike",
            index=models.Index(fields=["ip_address"], name="api_bloglik_ip_addr_5c4b15_idx"),
        ),
        migrations.AddIndex(
            model_name="commentlike",
            index=models.Index(fields=["ip_address"], name="api_comment_ip_addr_6fb02c_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["-created_at"], name="api_contact_created_b984ff_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["is_processed"], name="api_contact_is_proc_d0da9c_idx"),
        ),
        migrations.AddIndex(
            model_name="contactattempt",
            index=models.Index(fields=["ip_address", "-last_attempt"], name="api_contact_ip_addr_6b21f9_idx"),
        ),
    ]
