# Generated by Django 6.0.4 on 2026-06-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_bloglike_api_bloglik_ip_addr_5c4b15_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactattempt",
            name="failure_count",
            field=models.PositiveIntegerField(default=0, verbose_name="실패 횟수"),
        ),
    ]
