# Dependabot configuration for automated dependency updates
version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      testing:
        patterns:
          - "@testing-library/*"
          - "jest*"
          - "playwright*"
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    ignore:
      # Ignore React 19 until we're ready for migration
      - dependency-name: "react"
        versions: ["19.x"]
      - dependency-name: "react-dom"
        versions: ["19.x"]
      - dependency-name: "@types/react"
        versions: ["19.x"]
      - dependency-name: "@types/react-dom"
        versions: ["19.x"]
      # Ignore major versions that require manual migration
      - dependency-name: "framer-motion"
        update-types: ["version-update:semver-major"]
      - dependency-name: "web-vitals"
        update-types: ["version-update:semver-major"]
      # Ignore unstable Node 24
      - dependency-name: "node"
        versions: ["24.x"]
      # Dev dependencies with major changes
      - dependency-name: "eslint-plugin-jest"
        update-types: ["version-update:semver-major"]
      - dependency-name: "lint-staged"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@babel/core"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@babel/preset-env"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@babel/preset-react"
        update-types: ["version-update:semver-major"]

  # Backend dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci/cd"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"
    ignore:
      # Ignore Node 24 until it's stable
      - dependency-name: "node"
        versions: ["24-alpine", "24.*"]

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    labels:
      - "dependencies"
      - "docker"
      - "backend"
