FROM python:3.14.0-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gettext \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY requirements.txt .

# Install Python dependencies
RUN pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install watchdog[watchmedo]

# Copy project
COPY . .

# Expose port
EXPOSE 8000

# Run development server with auto-reload
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
