name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Build application
      run: |
        cd frontend
        npm run build
        
    - name: Run Lighthouse CI
      run: |
        cd frontend
        npm install -g @lhci/cli@0.13.x
        lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        
    - name: Upload Lighthouse results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: lighthouse-results
        path: frontend/.lighthouseci
        
    - name: Format results
      if: always()
      run: |
        cd frontend
        echo "## Lighthouse Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -f .lighthouseci/manifest.json ]; then
          echo "✅ Lighthouse CI completed successfully" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Lighthouse CI failed" >> $GITHUB_STEP_SUMMARY
        fi