name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Check update type
        run: |
          echo "Update type: ${{ steps.metadata.outputs.update-type }}"
          echo "Dependency names: ${{ steps.metadata.outputs.dependency-names }}"
          
      - name: Auto-approve patch and minor updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Comment on major updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-major'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const comment = `⚠️ **Major Version Update Detected**
            
            This PR contains major version updates which may include breaking changes:
            - ${{ steps.metadata.outputs.dependency-names }}
            
            Please review carefully before merging.`;
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: comment
            });
            
      # Block Node.js 24 updates (too new, not stable)
      - name: Close Node 24 updates
        if: contains(steps.metadata.outputs.dependency-names, 'node') && contains(github.event.pull_request.title, '24')
        run: |
          gh pr close "$PR_NUMBER" --comment "Node.js 24 is not yet stable. Keeping Node.js 20 LTS."
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Block React 19 updates (major breaking changes)
      - name: Close React 19 updates  
        if: contains(steps.metadata.outputs.dependency-names, 'react') && contains(github.event.pull_request.title, '19')
        run: |
          gh pr close "$PR_NUMBER" --comment "React 19 has major breaking changes. Manual migration required."
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}